import type { Theme } from "../types";

export const caffeine: Theme = {
  id: "caffeine",
  name: "Caffeine",
  description: "Warm coffee tones — cream and espresso.",

  variants: {
    dark: {
      colors: {
        background: "#111111",
        foreground: "#eeeeee",
        card: "#191919",
        cardForeground: "#eeeeee",
        popover: "#191919",
        popoverForeground: "#eeeeee",
        primary: "#ffe0c2",
        primaryForeground: "#081a1b",
        secondary: "#393028",
        secondaryForeground: "#ffe0c2",
        muted: "#222222",
        mutedForeground: "#b4b4b4",
        accent: "#2a2a2a",
        accentForeground: "#eeeeee",
        destructive: "#e54d2e",
        border: "#201e18",
        input: "#484848",
        ring: "#ffe0c2",
        sidebar: "#18181b",
        sidebarForeground: "#f4f4f5",
        sidebarPrimary: "#ffe0c2",
        sidebarPrimaryForeground: "#081a1b",
        sidebarAccent: "#27272a",
        sidebarAccentForeground: "#f4f4f5",
        sidebarBorder: "#27272a",
        sidebarRing: "#d4d4d8",
        radius: "0.5rem",
      },

    },
    light: {
      colors: {
        background: "#f9f9f9",
        foreground: "#202020",
        card: "#fcfcfc",
        cardForeground: "#202020",
        popover: "#fcfcfc",
        popoverForeground: "#202020",
        primary: "#644a40",
        primaryForeground: "#ffffff",
        secondary: "#ffdfb5",
        secondaryForeground: "#582d1d",
        muted: "#efefef",
        mutedForeground: "#646464",
        accent: "#e8e8e8",
        accentForeground: "#202020",
        destructive: "#e54d2e",
        border: "#d8d8d8",
        input: "#d8d8d8",
        ring: "#644a40",
        sidebar: "#fbfbfb",
        sidebarForeground: "#252525",
        sidebarPrimary: "#343434",
        sidebarPrimaryForeground: "#fbfbfb",
        sidebarAccent: "#f7f7f7",
        sidebarAccentForeground: "#343434",
        sidebarBorder: "#ebebeb",
        sidebarRing: "#b5b5b5",
        radius: "0.5rem",
      },

    },
  },
};
