import type { Theme } from "../types";

export const catppuccin: Theme = {
  id: "catppuccin",
  name: "Catppuccin",
  description: "Soothing pastel dark theme (latte is a variation for light).",
  variants: {
    light: {
      colors: {
        background: "#eff1f5",
        foreground: "#4c4f69",
        card: "#e6e9ef",
        cardForeground: "#4c4f69",
        popover: "#e6e9ef",
        popoverForeground: "#4c4f69",
        primary: "#8839ef",
        primaryForeground: "#eff1f5",
        secondary: "#ccd0da",
        secondaryForeground: "#4c4f69",
        muted: "#e6e9ef",
        mutedForeground: "#7c7f93",
        accent: "#fe640b",
        accentForeground: "#eff1f5",
        destructive: "#d20f39",
        border: "#ccd0da",
        input: "#ccd0da",
        ring: "#8839ef",
        sidebar: "#e6e9ef",
        sidebarForeground: "#4c4f69",
        sidebarPrimary: "#8839ef",
        sidebarPrimaryForeground: "#eff1f5",
        sidebarAccent: "#dce0e8",
        sidebarAccentForeground: "#4c4f69",
        sidebarBorder: "#ccd0da",
        sidebarRing: "#8839ef",
      },
    },
    dark: {
      colors: {
        background: "#1e1e2e",
        foreground: "#cdd6f4",
        card: "#181825",
        cardForeground: "#cdd6f4",
        popover: "#181825",
        popoverForeground: "#cdd6f4",
        primary: "#cba6f7",
        primaryForeground: "#1e1e2e",
        secondary: "#313244",
        secondaryForeground: "#cdd6f4",
        muted: "#303036",
        mutedForeground: "#a6adc8",
        accent: "#f5c2e7",
        accentForeground: "#1e1e2e",
        destructive: "#f38ba8",
        border: "#313244",
        input: "#313244",
        ring: "#cba6f7",
        sidebar: "#181825",
        sidebarForeground: "#cdd6f4",
        sidebarPrimary: "#cba6f7",
        sidebarPrimaryForeground: "#1e1e2e",
        sidebarAccent: "#26263a",
        sidebarAccentForeground: "#cdd6f4",
        sidebarBorder: "#313244",
        sidebarRing: "#cba6f7",
      },
    },
  },
};
