import type { Theme } from "../types";

/** 化学实验室配色（默认主题）：清新蓝白，突出教学界面。 */
export const chemLab: Theme = {
  id: "chem-lab",
  name: "化学实验室",
  description: "清新蓝白 · 化学课堂默认配色",

  variants: {
    light: {
      colors: {
        background: "#f4f7fc",
        foreground: "#16213a",
        card: "#ffffff",
        cardForeground: "#16213a",
        popover: "#ffffff",
        popoverForeground: "#16213a",
        primary: "#2563eb",
        primaryForeground: "#ffffff",
        secondary: "#e9eef8",
        secondaryForeground: "#16213a",
        muted: "#eef2f9",
        mutedForeground: "#5b6b85",
        accent: "#7c5cff",
        accentForeground: "#ffffff",
        destructive: "#e5484d",
        border: "#dde5f1",
        input: "#cfdaea",
        ring: "#2563eb",
        sidebar: "#e9eff9",
        sidebarForeground: "#16213a",
        sidebarPrimary: "#2563eb",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#dde7f7",
        sidebarAccentForeground: "#16213a",
        sidebarBorder: "#d6e0ef",
        sidebarRing: "#2563eb",
        radius: "0.75rem",
      },
    },
    dark: {
      colors: {
        background: "#0b1220",
        foreground: "#e7edf8",
        card: "#131c30",
        cardForeground: "#e7edf8",
        popover: "#182338",
        popoverForeground: "#e7edf8",
        primary: "#5b9bff",
        primaryForeground: "#081120",
        secondary: "#1c2840",
        secondaryForeground: "#e7edf8",
        muted: "#111a2c",
        mutedForeground: "#8b9bb8",
        accent: "#8f7bff",
        accentForeground: "#ffffff",
        destructive: "#f2555a",
        border: "#223051",
        input: "#223051",
        ring: "#5b9bff",
        sidebar: "#0e1626",
        sidebarForeground: "#e7edf8",
        sidebarPrimary: "#5b9bff",
        sidebarPrimaryForeground: "#081120",
        sidebarAccent: "#1a2540",
        sidebarAccentForeground: "#e7edf8",
        sidebarBorder: "#1e2a48",
        sidebarRing: "#5b9bff",
        radius: "0.75rem",
      },
    },
  },
};
