import type { Theme } from "../types";

export const claude: Theme = {
  id: "claude",
  name: "Claude",
  description: "Warm clay accent on paper.",

  variants: {
    dark: {
      colors: {
        background: "#1f1e1d",
        foreground: "#f5f4ee",
        card: "#262624",
        cardForeground: "#f5f4ee",
        popover: "#262624",
        popoverForeground: "#f5f4ee",
        primary: "#d97757",
        primaryForeground: "#1f1e1d",
        secondary: "#2a2926",
        secondaryForeground: "#f5f4ee",
        muted: "#2a2926",
        mutedForeground: "#b0a89a",
        accent: "#2f2d2a",
        accentForeground: "#f5f4ee",
        destructive: "#e5634d",
        border: "rgba(245,244,238,0.10)",
        input: "rgba(245,244,238,0.14)",
        ring: "#d97757",
        sidebar: "#1a1918",
        sidebarForeground: "#f5f4ee",
        sidebarPrimary: "#d97757",
        sidebarPrimaryForeground: "#1f1e1d",
        sidebarAccent: "#2f2d2a",
        sidebarAccentForeground: "#f5f4ee",
        sidebarBorder: "rgba(245,244,238,0.10)",
        sidebarRing: "#d97757",
        radius: "0.5rem",
      },

    },
    light: {
      colors: {
        background: "#faf9f5",
        foreground: "#3d3a2f",
        card: "#ffffff",
        cardForeground: "#3d3a2f",
        popover: "#ffffff",
        popoverForeground: "#3d3a2f",
        primary: "#c15f3c",
        primaryForeground: "#ffffff",
        secondary: "#f0eee6",
        secondaryForeground: "#3d3a2f",
        muted: "#efece4",
        mutedForeground: "#73705f",
        accent: "#f0ede4",
        accentForeground: "#3d3a2f",
        destructive: "#c0392b",
        border: "rgba(61,58,47,0.12)",
        input: "rgba(61,58,47,0.16)",
        ring: "#c15f3c",
        sidebar: "#f5f4ee",
        sidebarForeground: "#3d3a2f",
        sidebarPrimary: "#c15f3c",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#eceae0",
        sidebarAccentForeground: "#3d3a2f",
        sidebarBorder: "rgba(61,58,47,0.12)",
        sidebarRing: "#c15f3c",
        radius: "0.5rem",
      },

    },
  },
};
