import type { Theme } from "../types";

export const tide: Theme = {
  id: "tide",
  name: "Tide",
  description: "Deep slate with muted teal.",

  variants: {
    dark: {
      colors: {
        background: "#14191c",
        foreground: "#cdd9da",
        card: "#1a2024",
        cardForeground: "#cdd9da",
        popover: "#1a2024",
        popoverForeground: "#cdd9da",
        primary: "#6cb6b0",
        primaryForeground: "#14191c",
        secondary: "#232c30",
        secondaryForeground: "#cdd9da",
        muted: "#232c30",
        mutedForeground: "#93a3a4",
        accent: "#283330",
        accentForeground: "#cdd9da",
        destructive: "#e07a6a",
        border: "rgba(205,217,218,0.09)",
        input: "rgba(205,217,218,0.13)",
        ring: "#6cb6b0",
        sidebar: "#101517",
        sidebarForeground: "#cdd9da",
        sidebarPrimary: "#6cb6b0",
        sidebarPrimaryForeground: "#14191c",
        sidebarAccent: "#283330",
        sidebarAccentForeground: "#cdd9da",
        sidebarBorder: "rgba(205,217,218,0.09)",
        sidebarRing: "#6cb6b0",
        radius: "0.5rem",
      },

    },
    light: {
      colors: {
        background: "#f2f6f5",
        foreground: "#2b3a39",
        card: "#ffffff",
        cardForeground: "#2b3a39",
        popover: "#ffffff",
        popoverForeground: "#2b3a39",
        primary: "#2f7d76",
        primaryForeground: "#ffffff",
        secondary: "#e3ecea",
        secondaryForeground: "#2b3a39",
        muted: "#e6eceb",
        mutedForeground: "#5f6e6d",
        accent: "#e3ecea",
        accentForeground: "#2b3a39",
        destructive: "#c0392b",
        border: "rgba(43,58,57,0.12)",
        input: "rgba(43,58,57,0.16)",
        ring: "#2f7d76",
        sidebar: "#e9efed",
        sidebarForeground: "#2b3a39",
        sidebarPrimary: "#2f7d76",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#dde7e4",
        sidebarAccentForeground: "#2b3a39",
        sidebarBorder: "rgba(43,58,57,0.12)",
        sidebarRing: "#2f7d76",
        radius: "0.5rem",
      },

    },
  },
};
